framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware: [GOG\Application\Middleware\UnitOfWorkMiddleware]
            query.bus: ~
